### ISSUE TITLE
Feature Req - Sensor that works constantly without timing limits

### ISSUE THREAD

**Issue by cemac-ccs** [cemac/BBSensor#10]
@jimmcquaid has requested that a branch of the code be created which collects data regardless of the time so as to allow testing of the data collection and storage. 
This would be effectively the same as the static sensor code, except it would also get data from the gps

**Comment by wolfiex** [comment]
@jimmcquaid do you want this to upload data continuously as well? If so at what frequency?

**Comment by wolfiex** [comment]
Addressed by enabling CSV mode in #28
