### ISSUE TITLE
Feature Req - RTC to be added to server to allow it to function as a time source without internet

### ISSUE THREAD

**Issue by cemac-ccs** [cemac/BBSensor#11]
Internet connection cannot be guaranteed at all times, and so a ntp server should be run on the serverpi fed by a RTC module. 
Changes should also be made to the sensorpis to have the serverpi act as the source for their ntp requests.

**Comment by wolfiex** [comment]
Work done towards this - awaiting prototypes
Alarm/wake on pin not working at the moment

**Comment by wolfiex** [comment]
Completed.  Coded for two RTC. The latest work well, just the breakout board on those purchased have not connected the alarm pin.
