### ISSUE TITLE
Copy:  Edit New issue Portable sensor data from pilot not uploading to AWS #1

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#30]
Copy of Issue from cemac/SensorMod as Kirsty put it in the wrong repo.

The pilot data all has a single SERIAL number on it (00000000d5bbc3d4) and a single location (according to Dan, I haven't decoded the locations). Which implies that the data from the PORTABLEPi aren't uploading to the SERVERPi.

Three possibilities:

PORTABLEPi aren't logging any data
PORTABLEPI aren't transferring data to the SERVERPI
SERVERPI is not uploading the PORTABLEPi data (but is uploading it's own data - problem with merging algorithm?
@cemac-ccs will send Jim instructions as to how to copy the SERVERPi SD card, so we can look and see if PORTABLEPi data is logged there.

Could Jim do the USB trick to download data from the PORTABLEPi and @KirstyPringle can check that the PORTBABLEPi are logging data?

**Comment by KirstyPringle** [comment]
Copy of Answer from C. Symonds:

The data has now been downloaded manually from card images supplied by Jim, and csvs of the portable sensor data with no location data have been added to the Teams area, as have the logs from the run. db files have also been uploaded to aws.

Looking at the logs, it appears that possibility 2 is the culprit - the data is being collected but not uploaded to the serverpi. The error message that is generated when the upload fails refers to 'Nonetype is not callable', implying that a particular function is not being used correctly. I will update here once I have done some more testing, but currently the problem is either:

A problem in the software that was missed during testing
A problem in the hardware (for example casing or bumbags impeding the signal) that is interfering with the connection and generating a red-herring error message
Due to the use of the pysftp library, red herring error messages are unfortunately a distinct possibility however I strongly suspect that the issue is with software

**Comment by KirstyPringle** [comment]
Copy of comment from J. McQuaid:

I think it is software linked given the portable sensors were taken out of the bumbags to access the microSD cards and never returned, now sitting ontop of freezer next to serverpi. The portable units are built into a plastic box, I would be very surprised if there blocked the wifi signal between portable and server

**Comment by KirstyPringle** [comment]
So I think we are at a point where @cemac-ccs has established that for some reason the data is not transferred from the PORTABLEPi aren't transferring data to the SERVERPi.

But the PORTABLEPi are logging data and the SERVERPi is uploading data, it's the middle step that is missing.

@cemac-ccs and @wolfiex any updates on this?

**Comment by cemac-ccs** [comment]
Yes, the culprit appears to be line 177 of sensorpi/uploads/__init__.py. If this line is commented out, the upload occurs correctly.

I will make a pull request for this tomorrow once I have dealt with Dan's pull req.

Thanks

Chris
___________________________________________________________
Chris Symonds l  Software Development Scientist  l  CEMAC  l
School of Earth and Environment  l  University of Leeds  l  LS2 9JT  l  0113 3438668
________________________________

**Comment by wolfiex** [comment]
Sounds good to me (From what I can see this matches what you wrote in the
email. Good work!

Daniel

**Comment by cemac-ccs** [comment]
Changes for this have been made and put into the SensorMod repo. Will leave this ticket open until confirmation that it is working properly on the prototype setup.

**Comment by cemac-ccs** [comment]
Will require review and accept of PR #37 and #39

**Comment by cemac-ccs** [comment]
Data confirmed to be uploading correctly, now that the above PRs have been merged in. Closing
