### ISSUE TITLE
Data logged with a large number of decimal places - leading to large file sizes

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#31]
This is an easy one to fix (I think!) but I wanted to log it. 

At the moment all the data in each size category is being logged to > 6 significant figures, we can reduce this and also reduce the file size.

@wolfiex at some point would it be possible to add a step in the code that reduced the number of significant figures the data is being stored with?

**Comment by wolfiex** [comment]
A 'real' python float takes the same space as a single text character. The file size is only an issue if you use a text based storage format (CSV) as opposed to the database directly.  

Converting from numerical to text, and reducing the significant figures will have the opposite effect.

**Comment by KirstyPringle** [comment]
Okay, thanks. I think I'll close this and start a new issue to discuss the final file format / file size and naming convention, because I think that is worth discussing.
