### ISSUE TITLE
Temporary change to logging time for the portable sensors

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#34]
Hi Everyone,

Please can we temporarily change the PORTABLEPi code so they log continuously from 7 am to 7 pm rather than just logging during the school run times?

This would make it easier to gather testing data from the PORTABLEPi as we won't be reliant on testing them in the short morning and afternoon periods.

**!!!!! We need to remember to change this back before the schools monitoring !!!!**

Thanks!
Kirsty

**Comment by jimmcquaid** [comment]
sounds great, this would be very useful.
Thanks all,
Jim

**Comment by cemac-ccs** [comment]
Dan has added code to write to CSV for testing. If I am reading the code correctly it will run constantly with no upload attempts and write all data to a CSV which can then be taken off the sensor using the USB drive plugin method he added in Pull requests #12 and #18

There is also a system where you can use the staticsensor branch with a GPS plugged in to create an alway-on sensor that does upload and writing to db files, as per issue #10 and PR #27

**Comment by wolfiex** [comment]
I have just disabled the CSV testing, and enabled 'continuous mode' independently   #

The CSV switch is still active and can be triggered on individual sensors - Note if doing this the main file will not update as there will be a mismatch between data (so keep in mind which sensors are 'edited'

**Comment by cemac-ccs** [comment]
Closing this as continuous mode is now implemented and proven to work
