### ISSUE TITLE
Possibly combining branches?

### ISSUE THREAD

**Issue by cemac-ccs** [cemac/BBSensor#40]
Should the branches be combined, with just different versions of the __main__ file in subfolders rather than on different branches?

Now that the SensorMod repo has all the modules, what are the differences between branches outside __main__.py?

**Comment by wolfiex** [comment]
Could we have an argument which specifies which set to import from within the main file?

**Comment by cemac-ccs** [comment]
That's a good point. That is probably the way forward, or splitting out the divergent parts into functions. Would it be a bad idea to use the hostname to auto-determine which way to go?

**Comment by wolfiex** [comment]
We could use the $USER env variable `sensorpi` and `serverpi` also
  - Will either of these pose an issue if we have a unit that changes function?
  -  I think that is only a problem between the base stations and the portable sensors.

**Comment by wolfiex** [comment]
![image](https://user-images.githubusercontent.com/15582577/109057430-a00b2d80-76d9-11eb-9be3-aa3c405e3186.png)

**Comment by cemac-ccs** [comment]
First step to this is in PR #45 which merges portable and static sensors

**Comment by cemac-ccs** [comment]
Funny you should mention.....

Thanks

Chris
___________________________________________________________
Chris Symonds l  Software Development Scientist  l  CEMAC  l
School of Earth and Environment  l  University of Leeds  l  LS2 9JT  l  0113 3438668
________________________________

**Comment by cemac-ccs** [comment]
This has now been completed with the merging of PR #46
