### ISSUE TITLE
Polling of the OPC / fan shut down causing erroneous values

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#47]
At the moment the pi is polling the OPC at 1Hz for a certain time period, then it stops the OPC running while it writes the data to file (which takes a few seconds) then the fan restarts and the OPC is polled again.  But the first measurement after writing is anomalously low (probably because the fan isn't fully running yet).

There are three possible options:

1) Simply discard the first measurement (or two) after the fan restarts
2) Look into different polling frequencies to minimise this
3) Would it be possible to run the polling and the writing in parallel?  So we aren't starting and stopping the fan all the time?

I've spoke to @wolfiex after finding the strange values who suggested the fan explanation. 

Thanks,
Kirsty

**Comment by wolfiex** [comment]
It is possible to keep the fan on I believe, and keep things running the
same way. That will tell us if its the problem or something else.

What were the sf and error values associated with the low results?

**Comment by KirstyPringle** [comment]
Hi,
The SP (sampling period) values are normally 1.11  but they are 12s on the erroneous values, not sure what you mean by the error values?  The PM3 erroneous values are around 0.1 when the other values are around an order of magnitude larger.  You see it in all PM categories (not looked at the bins) but not in T and RH.  The values themselves are not impossibly low, it's more that there is a pattern of low every 10 or 11th value.
Thanks,
Kirsty

**Comment by wolfiex** [comment]
The RC column should correspond to the glitch count (error).

Daniel

**Comment by KirstyPringle** [comment]
Dan implemented a fix for this on 19.03.21 which changes to polling for data every 20s and lets the fan run continuously.

I am not sure if other changes were also made.

With this fix the fan does run continuously and the polling is 20s, but the PM values returned since this change are much lower (about 50* lower).

Blue line is the commercial PurpleAir Sensor
Red line is our sensor.  With the exception of a few high values, all values since the change are now < 1 ug m-3, with a clear change in baseline.

Changing the polling frequency clearly shouldn't change the values returned.  Our sensor values don't look similar to the Purple Air values either before or after the fix, so I'm not sure if there is something else going on?

@wolfiex could you possibly advise?  

![Timeseries](https://user-images.githubusercontent.com/20555920/111919463-fde52800-8a81-11eb-97f1-7590b3a5e865.png)

**Comment by wolfiex** [comment]
The continuous fan was to fix the erroneous data points which appeared
periodically - is this still a problem?

I am still not sure about the value difference. There are a few things we
could try to debug the problem:

Are yourself or Jim able to specify what the main differences between the
two sensors (and how they sample) are? Neither myself, nor Chris, are
experimentalists, and therefore how units perform beyond the specification
sheets is not within the scope of our expertese.

Additionally, what happens when adding the errors to each, I expect the R1
has much greater errors than something like the N2. How do these change (
especially at the limits of sensitivity for each instrument? ).

*Most importantly, what happens when you run another bbsensor unit
alongside. Could there be a chance that the current R1 has gotten clogged
or knackered somehow in the testing. Similarly, are you using the R1
outside the enclosure? Could the temperature affect its reliability? *

An alternative test would to plug the R1 into a windows computer and
compare the results provided by the alpha sense software. I would keep the
R1 location the same, however (e.g. within the bag) to reduce the external
variables we change when debugging.

**Comment by KirstyPringle** [comment]
Thanks Dan,

_The continuous fan was to fix the erroneous data points which appeared
periodically - is this still a problem?_  Sorry! I forgot to say, yes that is now fixed, thanks.

Since the fix with the fan, however, the values my sensor is logging is 50* lower than before the fix.  There is very seldom a value >1 ug m-3, which isn't the right magnitude.    

I don't understand how it can be possible that polling the data at a different frequency should change the value of the data?  So I'm not convinced it's getting the data correctly.  I am not sure what could be happening.

It was more of a comment that our sensor doesn't compare well to the PurpleAir:  I can explore this.  Jim's been running sensors side by side for a week now so we have the data from that.  Even though the sensors are different designs the timeseries are very different; I would expect both to pick out similar peaks and trends if the magnitudes differ.  I could have a duff sensor.   

_An alternative test would to plug the R1 into a windows computer and
compare the results provided by the alpha sense software.…_

I didn't know that this was possible, I will give it a try.  Thanks!

**Comment by wolfiex** [comment]
I wonder if we need to divide the value by the sampling period or something
of the sort?

**Comment by wolfiex** [comment]
Arduino Leonardo stats indoors

```python
Datalogger firmware ver OPC-R1-01(UNOr3)(res divider on SS)
OPC-R1 178630315                                            
OPC-R1 FirmwareVer=2.21...................................BS
BinBoundaries(ADC),0,27,57,95,140,205,296,473,682,920,1184,1473,1786,2123,2481,2861,4095
BinBoundaries(um),0.35,0.70,1.10,1.50,1.90,2.40,3.00,4.00,5.00,6.00,7.00,8.00,9.00,10.00,11.00,12.00,12.40
BinWeightings,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65,1.65
GSC,1.00
TOFtoSFRfactor,90
M_A(um),1.00
M_B(um),2.50
M_C(um),10.00
PVP(us),1.00
PowerStatus,3
MaxTOF(us),85.31
LaserDAC,244
BinWeightingIndex,2
Time(ms),Bin00,Bin01,Bin02,Bin03,Bin04,Bin05,Bin06,Bin07,Bin08,Bin09,Bin10,Bin11,Bin12,Bin13,Bin14,Bin15,MToFBin1(us),MToFBin3,MToFBin5,MToFBin7,SFR(ml/s),T(C),RH(%),SampPrd(s),#RejectGlitch,#RejectLong,PM_A(ug/m^3),PM_B,PM_C,Checksum
16182,0,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,8.67,0.00,0.00,0.00,2.568,25.9,27.6,1.016,0,0,0.734,1.588,1.634,47782
17218,0,4,2,0,1,0,1,0,1,0,0,0,0,0,0,0,11.33,0.00,0.00,0.00,2.573,25.9,27.5,1.023,0,0,0.966,7.814,61.152,6617
18255,0,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,38.00,0.00,0.00,0.00,2.398,25.9,27.4,1.023,0,0,0.855,2.605,2.726,40680
19292,0,1,3,1,0,1,0,0,0,0,0,0,0,0,0,0,6.67,12.67,22.67,0.00,2.417,26.0,27.3,1.023,0,0,0.855,6.362,10.417,53122
20329,0,2,3,0,1,0,0,0,0,0,1,0,0,0,0,0,6.33,0.00,0.00,0.00,2.456,26.0,27.3,1.023,0,0,0.903,4.594,95.777,54058
21365,0,8,0,0,1,1,0,0,1,0,0,0,0,0,0,0,17.67,0.00,17.00,0.00,2.333,26.1,27.2,1.023,0,0,1.296,8.168,59.523,34813
22403,0,4,3,1,1,0,1,0,0,0,0,0,0,0,0,0,20.67,14.00,0.00,0.00,2.248,26.1,27.2,1.023,0,1,1.470,9.883,23.160,16982
23439,0,7,1,0,0,1,0,0,0,1,0,0,0,0,0,1,16.33,0.00,20.00,0.00,2.196,26.1,27.1,1.023,0,0,1.341,5.603,245.197,814
24476,0,5,2,1,1,1,0,0,0,0,0,0,0,0,0,1,17.33,12.00,18.33,0.00,2.152,26.2,27.0,1.023,0,2,1.495,9.798,179.495,32145
Waiting until next cycle
76181,0,8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,8.67,0.00,16.00,0.00,2.252,26.1,27.9,1.016,0,1,1.277,5.011,8.970,26507
77217,0,6,2,1,0,0,0,0,0,0,0,0,0,0,0,0,16.00,11.67,0.00,0.00,2.212,26.1,27.6,1.023,0,1,1.540,4.593,5.012,21429
78255,0,4,1,1,1,1,1,0,0,0,0,0,0,0,0,0,8.67,12.67,20.67,0.00,2.263,26.1,27.5,1.023,0,0,1.067,11.191,28.191,20647
79292,0,5,1,0,1,0,1,1,1,0,0,0,0,0,0,0,11.00,0.00,0.00,22.67,2.293,26.1,27.3,1.023,0,0,1.046,10.301,96.951,37231
80328,0,6,2,1,1,0,0,0,0,0,0,0,0,0,0,0,9.67,13.00,0.00,0.00,2.349,26.2,27.3,1.023,0,0,1.522,6.469,8.043,32024
81366,0,7,3,0,0,0,0,0,0,0,0,0,0,0,0,0,9.33,0.00,0.00,0.00,2.417,26.2,27.2,1.023,0,1,1.587,3.808,3.941,64233
82402,0,6,2,0,1,0,0,0,0,0,0,0,0,0,0,0,7.67,0.00,0.00,0.00,2.504,26.2,27.1,1.023,0,0,1.279,4.777,5.972,17497
83439,0,2,3,0,2,0,1,0,0,0,0,0,0,0,0,0,15.67,0.00,0.00,0.00,2.479,26.3,27.0,1.023,0,0,0.962,9.212,22.081,45351
84475,0,4,2,1,0,0,0,0,0,0,0,0,0,0,0,0,6.67,13.33,0.00,0.00,2.551,26.3,26.9,1.023,0,0,1.056,3.520,3.879,20096
Waiting until next cycle
136181,0,4,1,1,1,0,0,0,0,0,0,0,0,0,0,1,9.33,13.67,0.00,0.00,2.584,26.2,27.3,1.016,0,0,0.941,4.801,143.603,32769
137219,0,8,1,0,1,0,3,1,0,0,0,0,0,0,0,1,16.00,0.00,0.00,81.33,2.474,26.2,27.1,1.023,0,2,1.402,14.397,214.609,16695
138255,0,5,1,2,0,3,0,0,1,0,1,0,0,0,0,0,12.33,13.33,19.67,0.00,2.471,26.3,27.1,1.023,0,1,1.205,13.505,157.988,11786
139292,0,6,2,1,1,0,0,0,1,2,0,0,0,0,0,0,14.67,16.00,0.00,0.00,2.425,26.3,27.5,1.023,0,0,1.474,7.423,189.319,29660
140329,0,4,3,1,1,0,0,1,1,0,0,0,0,0,0,0,6.33,12.33,0.00,20.00,2.501,26.3,28.1,1.023,0,2,1.321,9.246,78.615,36595
141367,0,87,2,0,2,1,0,0,1,0,0,0,0,0,0,1,20.00,0.00,16.00,0.00,1.875,26.3,28.7,1.023,0,10,17.217,39.540,293.308,45420
142403,1,112,4,1,0,0,0,1,0,0,1,0,0,0,0,1,19.00,17.00,0.00,25.00,1.714,26.4,28.8,1.023,0,11,24.642,47.187,418.593,49443
143440,0,221,4,4,0,0,0,0,0,0,0,0,0,0,0,0,18.33,16.67,0.00,0.00,1.674,26.4,29.0,1.023,1,32,49.064,89.733,92.451,32639
144478,0,50,3,0,0,0,0,0,0,0,0,0,0,0,0,0,15.33,0.00,0.00,0.00,1.792,26.4,29.7,1.023,0,9,10.705,19.312,19.639,19273
Waiting until next cycle
ERROR Resetting SPI
ERROR Resetting SPI
ERROR Resetting SPI
ERROR Resetting SPI
```

**Comment by wolfiex** [comment]
https://github.com/cemac/BBSensor/commit/86b989ce4f8e3f5a9dd3feec072fafb05feb7e4f

Addressed
