### ISSUE TITLE
16 or 32 bit integers - update from alphasense

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#53]
Mark Giles from Alphasense emailed the below:

_Please find attached some slightly updated code for the Arduino-Uno.

Not sure if this will solve any of the issues you are seeing but the selection of 16 or 32 bit integers could lead to issues.  The Arduino Uno uses 16 as default so it didn't need setting many controllers use 32 as default

Let me know if we need another catch up on the R2s issue as I am not sure where we are_

Not urgent, but at some point I (Kirsty) will check this.

**Comment by wolfiex** [comment]
Does not seem to be an issue. Python uses reals by defaults
