### ISSUE TITLE
Shell script to 1) turn of OPC followed by 2) reboot 

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#57]
In the schools we are trying to avoid going into the classrooms as much as possible, so we are rebooting etc. from outside the classroom, but we need to go into the classroom to do the pin thing to shut down the OPC.

Is it possible to write a shell script that prompts the OPC to shutdown and then reboots the Pi?   

(so we can reboot without damaging the OPC and without needing to go into the classroom)

It would be useful for the outdoor statics too, as they are up high and hard to get to.

**Comment by wolfiex** [comment]
Implemented a temporary file to trigger a stop interrupt - similar to the GPIO using the `cleankill.py` file: located on the main level of THIS repository. 

## Example usage 
```
root@bbsensor00:~/BBSensor# python3 cleankill.py 
Stopfile created. 
 Waiting 20 seconds for code to terminate before force-stopping the R1 (incase of crash)
INFO        DB saved at 13:13:45
INFO        exiting - STOP: False
CRITICAL    natural death
INFO        Attempting to exit in a controlled Manner 
 2021-05-25 14:13:47.011437 

```

You can append a `sudo reboot -h now` or any other script after this should you wish.

**Comment by KirstyPringle** [comment]
Speedy! Thanks. 

So to reboot without hurting the OPC we can type:

1) python3 cleankill.py  - this will kill any running python code and shut down the OPC?
2) sudo reboot -h now  - if we want to reboot 


Thanks

**Comment by wolfiex** [comment]
That is correct.

Daniel
